BREAKING: Homie is about Lightweight topic discovery
homieiot/convention pull request #120
Opened 2018-10-31 13:50 UTC by davidgraeff

* $stats is fully optional
* Remove $fw, $mac and $localip completely. Those are all for firmware updates but at the same time not sufficient for a firmware update. Requires another spec, independent of how the topics are defined.
* Remove "retained" column where applicable. Because "retained" is per default on, as specified in the header. Makes the spec easier for the eyes.

2018-10-31 19:34 UTC, ThomDietrich commented
> remove $fw, $mac and $localip

I get your point regarding firmware update but are those not also good for simple self-announcement?

2018-10-31 20:59 UTC, davidgraeff commented
I don't think so. The Mac is required at the moment, but is not useful in an mqtt network where the broker can be in a different subnetwork. The localip attribute is flawed. Because an interface usually has more than one IP address nowadays. And it is the local IP only which is again not so useful for mqtt. And the $fw node is wrongly named, because a homie Linux client is technically not a firmware. 

I'm not really sure what the benefit is for a controller to know those information.

An administrative tool would usually want to know about the firmware to perform ota. That's why I think we should make this an add-on convention that specifies exactly all information for ota to work.

2018-11-02 02:34 UTC, boc-tothefuture commented
Are you proposing that we keep $implementation?

2018-11-02 09:42 UTC, davidgraeff commented
Yes, but optional. There might be quirks in some implementations and knowing the implementation together with the homie version might help a controller to overcome those quirks.

2018-11-02 09:59 UTC, boc-tothefuture commented
Would we want an optional implementation version as well?  Using the quirks scenario you would need that if the implementation evolved at a different rate than the homie version.

2018-11-02 13:24 UTC, davidgraeff commented
Might be a good idea, but is not part of this PR

2018-11-02 13:55 UTC, boc-tothefuture commented
I can open a PR on it, after this one is merged.

2018-11-03 03:26 UTC, timpur commented
Im with @ThomDietrich for $fw, $mac and $localip

MAC and IP are already required for the IP stack so why not just send them. Maybe make these optional ?

FW I think has quite alot of value actually. Maybe Implementation type makes more sense idk ?

Maybe these just need shuffling around where they should sit ? 

Not sure the pros over come the cons here. But I'll let you guys discus.

2018-11-03 06:39 UTC, davidgraeff commented
My controller and device implementations are both not homie compliant, because I don't publish or subscribe to those attributes and I'm not encouraging other device implementers to do so if they ask for the minimum compliance level.
I really thing this should be at least optional yes. Soon.

2018-11-03 10:07 UTC, boc-tothefuture commented
@timpur The problem is, which mac and IP address should be sent and does that have value in all situations?  If you have multiple interfaces and ip addresses, one can do some work with UDP sockets and figure out which IP and therefore interface the OS will use to get to the broker. That may have value, but that value reduces if your client is running in a docker container and routing out via a NAT and is not addressable on the network.

For firmware, lets say I am again running in a docker container and I am fetching and publishing weather information from weather.com over the homie convention. What would my firmware be?  The version of docker? The API version of the weather.com device I am fetching data from?  I think there are a lot of use cases where firmware doesn't make sense to be required. 

I think all of these values should be optional attributes under implementation because they are implementation specific.

2018-11-04 00:17 UTC, Thalhammer commented
> MAC and IP are already required for the IP stack so why not just send them. Maybe make these optional ?

No, they are not. IP does not require a mac to be present and many technologies which have no mac (almost everything which is not BT, WLAN or LAN). The most prominent example being 2G/3G/LTE.

2018-11-04 20:53 UTC, timpur commented
So lets all agree on what and where these things should go.

> I think all of these values should be optional attributes under implementation because they are implementation specific.

> I really think this should be at least optional yes.

So optional values sitting under implementation ? 

Also regarding foks who pointed out it doesnt always have to the mac and ip, why dont we reimagine these to allow for for options? eg `address = IP: 192.168.0.2, MAC: AB:12:CD:34:EF:56` (for standard IP networks) or `address = RF: 42` (for RF networks), also we could show the mqtt identifier `MQTT: esp1234`. Basically address is some network identifiers ?? It cold contain the full stack of identifiers that the implementation is using ?

2018-11-04 20:56 UTC, davidgraeff commented
@timpur: yeah that's all doable. But this PR is first about getting rid of Mac and localip and the other stuff that not all implementation need to have. Make a pr proposal for address or similiar

2018-11-04 21:16 UTC, timpur commented
@davidgraeff , yeah i agree with that, i can do so, will think a bit more on the matter first though.

2018-11-04 21:22 UTC, timpur requested changes
Looks good, please change the one comment.

2018-11-04 21:22 UTC, timpur commented on convention.md
> +    <td>Interval in seconds at which the device refreshes its <code>$stats/+</code>: See next section for details about statistical attributes</td>
This needs updating. something like this? eg Interval in seconds at which the device refreshes all other stats.

2018-11-04 22:45 UTC, davidgraeff commented on convention.md
> +    <td>Interval in seconds at which the device refreshes its <code>$stats/+</code>: See next section for details about statistical attributes</td>
done

2018-11-05 17:13 UTC, ThomDietrich commented
My thought was to make Mac and IP optional, so that clients can implement them, when meaningful. However this is once again nothing that has to be part of the convention. An implementer/user can always add additional data. I agree to remove IP and Mac.

2018-11-05 17:33 UTC, davidgraeff commented
@timpur Could you re-review and approve?

2018-11-05 20:42 UTC, timpur approved these changes

2018-11-05 21:00 UTC, timpur commented
@davidgraeff , sorry different time zone .... 

For anyone interested about the address stuff https://github.com/homieiot/convention/issues/129

2018-11-05 22:27 UTC, marvinroger approved these changes
As a reminder, the convention was initially created as part of the `homie-esp8266` project, so things like firmware, MAC address and IP address all made sense then.

Now that homie has a broader audience, I'm definitely for these changes!

2018-11-05 22:40 UTC, merged